---
- name: Package Management with Variables Demonstration
  hosts: all
  become: yes
  vars:
    web_server: nginx
    nginx_version:
    
    tools_package:
      - git
      - wget
  tasks:



    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      
    - name: Install multiple tools
      ansible.builtin.package:
        name: "{{ tools_package }}"
        state: present
        
    - name: Ensure nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    - name: Store web server version in variable
      ansible.builtin.command: nginx -v
      register: nginx_version_result
      changed_when: false