#SPDX-License-Identifier: MIT-0
---
# tasks file for apache-role
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present
  notify: Restart Apache

- name: Ensure Apache is started and enabled
  ansible.builtin.service:

    name: apache2
    state: started
    enabled: true

- name: Deploy custom index page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: Restart Apache

