
apiVersion: v1
kind: Service
metadata:
  name: web-app2-service
  namespace: web-app2
spec:
  selector:
    app: nginx-deploy  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP